"""create render_history table

Revision ID: 9efb14568497
Revises: 
Create Date: 2026-07-20 09:04:28.448361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efb14568497'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('render_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('css', sa.Text(), nullable=False),
    sa.Column('json_data', sa.JSON(), nullable=False),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('height_mm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_history_user_id'), 'render_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_render_history_user_id'), table_name='render_history')
    op.drop_table('render_history')
    # ### end Alembic commands ###
