"""create gemini_free_usage table

Revision ID: c364aae167e3
Revises: d5b2e7c48f10
Create Date: 2026-07-28 00:31:03.113805

Gemini無料枠（gemini_free）の利用回数を、全ユーザー共有の日次カウンタとして記録するテーブル。
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c364aae167e3"
down_revision: Union[str, None] = "d5b2e7c48f10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gemini_free_usage",
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("usage_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gemini_free_usage")
    # ### end Alembic commands ###
